### ISSUE TITLE
Please try one more time to replace the default package?

### ISSUE THREAD

**Issue by eugenesvk** [evandrocoan/WordCount#5]
I've noticed that you've already tried once to replace the default archived repo with your active fork https://github.com/wbond/package_control_channel/issues/6907

As far as I understood from the last comment after only a few years of delay ;) there was no objection https://github.com/wbond/package_control_channel/issues/6907#issuecomment-743807885, there are just a few asks from the ST folks:

> Can you make major releases for both

So maybe just create the an empty tag `2.0.0` with only the message below↓ (the original package is at version `1.0.0`)

> add message about anything that might break for existing users

Not sure what those would be (from what I've briefly read, you only added the great delay feature to avoid wasting CPU, hardly a break, but might be worth mentioning and saying that the package owner has changed)

>and then create PRs to replace the existing WordCount package?

I'd create a replacement PR updating the links, but don't want to add any confusion as to why it's not coming from the package owner

**Comment by evandrocoan** [comment]
I opened a pull request adding it: https://github.com/wbond/package_control_channel/pull/8629
