### ISSUE TITLE
Customizable status name to allow sorting

### ISSUE THREAD

**Issue by eugenesvk** [evandrocoan/WordCount#7]
Since status elements are sorted by name in ST, I usually add something like `statusName	= '08_WordCount' # number defines the order of custom status bar statuses` and then `view.set_status(statusName, status_text)`

But not that I've switch to you package, that customization is lost.
Do you mind adding another user config option that would allow prepending an index to the status name?

**Comment by evandrocoan** [comment]
I released a new version 2.1.0 with these changes.
