### ISSUE TITLE
Number of matched words is not appearing 

### ISSUE THREAD

**Issue by IGRACH** [evandrocoan/WordCount#9]
After the new update number of match words is not appearing when I use find command to find specific word/text.

With WordingStatus package:
![image](https://user-images.githubusercontent.com/7463331/209013940-fdf333cb-6762-4de3-b497-2b6dd0cebbde.png)

Without WorkingStatus package:
![image](https://user-images.githubusercontent.com/7463331/209014045-01a2a1a9-7eca-485e-9d5c-6b1c95b38d5c.png)

**Comment by evandrocoan** [comment]
So, you just need to restart sublime text after updating?
